### PR TITLE
install gettext for msgfmt

### PR DESCRIPTION
**Pull request by mmoll**
Related to https://github.com/OpenRailwayMap/OpenRailwayMap/pull/743, AFAICT.

### CODE REVIEW

**Comment by DerDakon** [comment]
Did you mean OpenRailwayMap/OpenRailwayMap#741? But msgfmt is there basically forever, it's msgmerge that is new.

**Comment by mmoll** [comment]
strange... well, I saw this:
```
TASK [Build MapCSS styles, JOSM presets and locales] ******************************************************************************************************************************************************************************************
changed: [dev.openrailwaymap.org] => (item=josm-presets)
changed: [dev.openrailwaymap.org] => (item=styles)
failed: [dev.openrailwaymap.org] (item=locales) => {"ansible_loop_var": "item", "changed": false, "cmd": "/usr/bin/make all", "item": "locales", "msg": "/bin/sh: 1: msgfmt: not found\nmake: *** [Makefile:18: ca_ES/LC_MESSAGES/messages.mo] Error 127", "rc": 2, "stderr": "/bin/sh: 1: msgfmt: not found\nmake: *** [Makefile:18: ca_ES/LC_MESSAGES/messages.mo] Error 127\n", "stderr_lines": ["/bin/sh: 1: msgfmt: not found", "make: *** [Makefile:18: ca_ES/LC_MESSAGES/messages.mo] Error 127"], "stdout": "msgfmt -o ca_ES/LC_MESSAGES/messages.mo ca_ES/LC_MESSAGES/messages.po\n", "stdout_lines": ["msgfmt -o ca_ES/LC_MESSAGES/messages.mo ca_ES/LC_MESSAGES/messages.po"]}

```

**Review by DerDakon — APPROVED** [review]
I don't object this, what do you think about splitting that line?

**Comment by mmoll** [comment]
> what do you think about splitting that line?

I'm in favour of this.

**Comment by DerDakon** [comment]
merged in https://github.com/OpenRailwayMap/server-admin/commit/4c2709a69992d16cf60d932a16658d507e7b78eb

**Pull request closed without merging**
